#!/usr/bin/env perl

use strict;
use warnings;

use JSON::MaybeXS;
use Path::Class::File;

my ($from, $to) = @ARGV;
die "Usage: $0 from_spec.json to_spec.json" if (not defined $from or not defined $to);

my $from_file = Path::Class::File->new($from);

my $file_content = $from_file->slurp;

# canonical so the output is always in the same order
my $json = JSON::MaybeXS->new(canonical => 1, pretty => 1, space_after => 1);

my $doc = $json->decode($file_content);

# Fix "Don't know how to handle type for property Parameters on AWS::DataBrew::Recipe.Action"
# The "PrimitiveType" is not present in the Parameters attribute. In the
# documentation it's empty
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-recipe-action.html#cfn-databrew-recipe-action-parameters
$doc->{PropertyTypes}{'AWS::DataBrew::Recipe.Action'}{Properties}{Parameters}{PrimitiveType} = 'Json';


my $dest_file = Path::Class::File->new($to);
$dest_file->spew($json->encode($doc));


